### ISSUE TITLE
GTK Transactions disappeared

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#10]
**USer 1**
I had transactions open on the platform, but after the platform did not work, they disappeared from me, neither the funds were returned nor the transactions are displayed. This is fine ?

I don't have screenshots. here is my address sif19hnwpgsk6xstvg4zmugsf9a2cnnp0c3d466xvd

**User 2**
My active trades and ongoing matches have disappeared. And I can't open a new position. Regardless of whether the trade was executed or there is not enough liquidity, the order does not appear anywhere. Here are my last two attempts
https://atomscan.com/sifchain/transactions/B512351EE1A1BFC5526631CBD93CC4B8C7C2A34B7C215A1CAD076E885DE522B9
https://atomscan.com/sifchain/transactions/006960D3E36788CD60859014988D95B84F15EE71D25555899C9F6CBAAB7D6047
At the same time, the balance decreases.

**Comment by ghuznee** [comment]
Max profit / stop loss - to do with this.

"1 user covered. I reported back to user on Discord plus see my messages on slack" - Piotr

**Comment by ghuznee** [comment]
Merge complete. Testing now. @sx0785 needs to push out

**Comment by ghuznee** [comment]
IT'S BEEN PUSHED OUT

**Comment by ghuznee** [comment]
User 2 still in progress

**Comment by pgoos** [comment]
Followed up on user 2 issues. Reached out to that user on Discord. After analysis, confirmed reported issues have been fixed. We should refund that user with 0.1 atom and 0.1 dai but the user didn't want to.
