### ISSUE TITLE
Remove 'Learn about us' link from https://sifchain.network/

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#116]
**Background:**
About Us information is now redundant and also broken. Need to remove the link for now and add at a later date.

**To Do**
1) Remove the link
2) Central justification for other 2 links

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0dtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af38139b4cfead47916cfe28b231c64edcf821c4/image.png)

**Comment by pgoos** [comment]
PR https://github.com/Sifchain/landing-page/pull/11
