### ISSUE TITLE
Update IBC - Go Version v4

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#129]
**Background:** 
Our current version makes Sifchain vunerable to attack

**Requirement:**
Update current IBC-GO version to the latest version

**To Do:** - 

- So what needs to be done:
- Take a snapshot of testnet
- Retrieve nodes private keys from Jure
- Create a localnet based on snapshot
- Apply PR changes and build new binary version
- Raise a software upgrade proposal with new changes
- Check if upgrade successful

1) TESTING COMPLETE in 2 days (depending on speed of getting private keys)
2) Then need to deploy and push to main net, validators (raise a proposal) 
Consider governance standard for Sifchain. 

**Notes:**
https://github.com/atheeshp/sifnode/commit/95c4f970cdd2eff81463141e3c8b73311bf4f4c9

**Comment by ghuznee** [comment]
Hey @jzvikart - can you please provide @snobbee the private keys if you can?

**Comment by ghuznee** [comment]
Someone needs to raise a proposal

**Comment by jzvikart** [comment]
Snapshot of testnet including private keys prepared, instructions sent to Caner.

**Comment by ghuznee** [comment]
Testing on Mainnet - hopefully completed by friday 27th
