### ISSUE TITLE
Stabilising the transaction data in GTK Margin

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#157]
**Background**
Currently the transaction data is not entirely stable, we need to address that

**User Story**
**As a** Trader
**I would like to** trust that the platform will be as stable as possible when facilitating data
**So that I can** feel much more confident in actioning trades

**Acceptance Criteria**

- Move the source code to correct repo
- Setup logging to sentry
- Enhance exception handling
- add code to financial messaging

**Comment by ghuznee** [comment]
@ghuznee to fill out with @monilpat 
or knowledge share

**Comment by sx0785** [comment]
deployed
