### ISSUE TITLE
Update new_margin_transaction job / clear db

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#20]
Description: Currently we are getting way too many transactions written to the db we need to clear test / prod dbs and update the job to only get relevant 
5.1 Clear both dbs 
5.2 Update job to filter properly 
5.3 Test it out

**Comment by ghuznee** [comment]
'if has memo then save it' - this is what it's been meaning huge amount of data
it's been tightened up to be more optimal
do filtering, indexing (speed up querying)

**Comment by ghuznee** [comment]
Was taking 4 seconds to process everything every time. We should now see quicker processing times thanks to optimisaiton.

**Comment by sx0785** [comment]
A txn filter has been applied and we should expect less data saving to our db

**Comment by sx0785** [comment]
Will work with Monil tmr to find out the query optimiztion.

The query currently is returning too much data and need to find a better way to achieve

**Comment by ghuznee** [comment]
In testing with Shawn
