### ISSUE TITLE
End to End Testing of Application

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#21]
Task 6: End to End Testing of Application
Description: Once everything is done we need to check all scenarios and test them out before we feel comfortable for launch
6.1 Trade side scenarios
6.2 Matcher Side scenarios
6.3 Analytics validation

**Comment by pgoos** [comment]
Most of e2e cases are now covered including automated trade closing.
Still left (not that easy to test against) to execute:
* trade liquidation
* trade max profit hit
