### ISSUE TITLE
Links aren't working on the Dex. -> Migration Work

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#28]
Sifchain.com reverts to https://landing-page-sifchain.vercel.app/

Should be: sifchain.network which works fine

1) **Documentation link** - https://docs.sifchain.finance/
Can see it here: https://web.archive.org/web/20230129223639/https://docs.sifchain.finance/welcome-to-sifchain/start-here

**ACTION:**
Need to migrate to docs.sifchain.network

FOUND THIS BUT WRONG DOC (DEV ONLY):
https://sifchain.stoplight.io/docs/sifchain/6enkuv8yb2xa3-getting-started

2) **Legal Disclaimer Link -** https://www.sifchain.finance/legal-disclaimer

Can see it here: https://web.archive.org/web/20230412224626/https://www.sifchain.finance/legal-disclaimer

**ACTION:**
Need to migrate to: sifchain.network/legal-disclaimer

3) **Learn About Us Link -** https://www.sifchain.finance/

Can see it here: https://web.archive.org/web/20230608021432/https://sifchain.finance/

ACTION:
@jkbrooks i'm not sure what was previously agreed, but I think we could just remove the About Us link entirely for now. What do you think? 

4) Sifchain.com -> redirections currently to https://landing-page-sifchain.vercel.app/

****ACTION:**
Redirect to sifchain.network**

**Comment by sx0785** [comment]
Documentation - https://docs.sifchain.finance/
Legal Disclaimer - https://www.sifchain.finance/legal-disclaimer
Learn About Us - https://www.sifchain.finance/

**Comment by ghuznee** [comment]
Legal Disclaimer should be a new page https://www.sifchain.network/legal-disclaimer

@sx0785 


Here's the copy:

Disclaimer
Rowan and eRowan are not being offered in the United States or to U.S. persons. The Sifchain DEX is not available to people or companies who are residents of, located, incorporated or have a registered agent in the United States. People or companies in restricted jurisdictions or embargoed by the United States, the United Kingdom or the European Union are also prohibited from using the Sifchain DEX. Use of a virtual private network to circumvent the restrictions is also prohibited.

NOTHING IN THIS POST SHALL CONSTITUTE OR BE CONSTRUED AS AN OFFERING OF SECURITIES OR AS INVESTMENT ADVICE, STRATEGY OR INVESTMENT RECOMMENDATIONS BY SIFCHAIN OR ANY OF ITS AFFILIATES.

Forward-looking Statements
This communication contains forward-looking statements that are based on our beliefs and assumptions and on information currently available to us. In some cases, you can identify forward-looking statements by the following words: “will,” “expect,” “would,” “intend,” “believe,” or other comparable terminology. These statements involve risks, uncertainties, assumptions, and other factors that may cause actual results or performance to be materially different. We cannot assure you that the forward-looking statements will prove to be accurate. These forward-looking statements speak only as of the date hereof. We disclaim any obligation to update these forward-looking statements.

Do you have the template for the font / text / colours etc?

**Comment by ghuznee** [comment]
Check cloudflare for a footprint of the subdomains

**Comment by ghuznee** [comment]
Jazear - to look for evidence of the migration work and the subsequent DNS activities
