### ISSUE TITLE
Margin Link is broken - grey it out

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#35]
Requirement:

_Grey it out_

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM29XQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f6e6730857c3baec4c41254b963aee9ac941a52/Screenshot%202023-10-09%20at%209.58.30%20AM.png)

Margin:
https://margin.sifchain.network/

**Comment by pgoos** [comment]
Prepared PR: https://github.com/Sifchain/sifchain-ui/pull/843

**Comment by ghuznee** [comment]
@snobbee to approve PR
