### ISSUE TITLE
SPIKE: Investigate Time Scale Feasiblity and Cost

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#42]
Time cost is 2.3K. We have a 6K bill.

This faciliates our data on Sifchain DEX

TO DO:
Feasibliy of alternative and cheaper means of running DB.

**Comment by ghuznee** [comment]
From @sx0785 

we need around 1TB storage
10:28
16GB memory & 4 v-cupus
10:31
image.png
 
image.png


10:32
$699 + $1.5 per GB *1024GB = $2300 per month

**Comment by sx0785** [comment]
https://cloud.digitalocean.com/registrations/new?refcode=f6fcd01aaffb
Found a better one 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTQyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--115131a1e592acc3559aeda9913d3c1e2427f440/image.png)
