### ISSUE TITLE
Create Subdomain + Add Sifchain Document to docs.sifchain.network

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#53]
**Background:**
Currently the Sifchain documentation is at docs.sifchain.finance. This is currently down, but regardless we are moving to .network domain anyway.

**The Goal**
The goal is to have Sifchain document accessible to users via: docs.sifchain.network. From there we can update the links in the Frontend.

**To do**
1) Create subdomain docs.sifchain.network (in Cloudflare?)
1b) Add a CNAME record

2) Go onto gitbook.com Sifchain
https://app.gitbook.com/o/-MPr1-EyDpmNpr6YzUUt/s/HPfKYBX5C609ImvucGUM/welcome-to-sifchain/start-here

3) Select Sifchain Documents Site on left menu

4) Select 'Share Button'

5) Publish to the web > Customize URL > Select 'Edit Domain'

6) Change domain to docs.sifchain.network > Select Next: Configure DNS

7) Configure DNS (change CNAME record)

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70579e56e1188bdc1d5e2aed0653bb5d87d8ff65/Screenshot%202023-10-18%20at%2013.06.28.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzlLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82f41fecc3361cd1ba31c378a07ef69018639843/Screenshot%202023-10-18%20at%2013.06.49.png)

https://docs.gitbook.com/publishing/custom-domain/configure-dns

**Comment by khdegraaf** [comment]
Appears to be working now.

**Comment by ghuznee** [comment]
@khdegraaf doesn't work for me: docs.sifchain.network

**Comment by khdegraaf** [comment]
Fixed.
