### ISSUE TITLE
GTK Issue - "Not displayed correctly withdraw"

### ISSUE THREAD

**Issue by ghuznee** [Sifchain/issues2.0#68]
**2 issues here happening:**

1) NaN that happens when you want to withdraw and you click Max button for a token that doesn’t have any unencumbered balance. When you switch to a different token, it still shows “NaN”. When you click Max for that token, amount is displayed properly

2) Using Max button doesn’t allow you to withdraw since it doesn’t deduct minimum token amount. We spoke about it yesterday

2nd issue is definitely high priority

**Comment by pgoos** [comment]
Done in https://github.com/Sifchain/financial_messaging/pull/340
